ConnectionStrings:
  DefaultConnection: "Server=127.0.0.1;Port=5432;Database=ss14;User Id=postgres;Password=postgres"
  AdminConnectionConnection: "Server=127.0.0.1;Port=5432;Database=ss14-admin;User Id=postgres;Password=postgres"
